= Improve this Doc

This extension post-processes HTML documentation, adding an 'Improve this Doc' button (the actual text is configurable).

It adds the button in two different locations.

* It always adds a button at the top of each generated top-level document

* It also adds a button for ``include::``'d child documents.

For this second use case, included sections must have an `id` that follows a specific naming convention.
(This is required because the extension is implemented as a post-processor, and as such does not have any visibility as to when an ``include::`` was actually performed).


[TIP]
====
For an example of the generated output, see the link:http://isis.apache.org/guides/ugfun.html[Apache Isis documentation].
====



== Example

For example, suppose we have:

.some-doc-or-other.adoc
[source,adoc]
----
[[some-doc-or-other]]
= Some Doc or Other

yada yada yada

\include::_some-doc-or-other_child-doc[leveloffset+=1]
----

with the included file as:

._some-doc-or-other_child-doc.adoc
[source,adoc]
----
[[_some-doc-or-other_child-doc]]
= Child Doc

yada yada yada
----


For the top-level document, the extension will always add an an 'improve this doc' button.

For the included document, because its `id` starts with `_{parentId}_xxx` (ie an underscore then the id of the parent section), then the extension will add an 'improve this doc' button here also.

This works over multiple levels.
If the child document in turn includes a grandchild document using:

._some-doc-or-other_child-doc.adoc
[source,adoc]
----
...
\include::_some-doc-or-other_child-doc_grandchild-doc[leveloffset+=1]
----

and the grandchild is in turn:

._some-doc-or-other_child-doc_grandchild-doc.adoc
[source,adoc]
----
[[_some-doc-or-other_child-doc_grandchild-doc]]
= Grandchild Doc

yada yada yada
----

then the extension will add a button for the grandchild also.

To suppress the button (that is, for a section that is not in its own document) you can either choose an `id` for the section that doesn't follow this convention, or omit the `id` together.

For example:

._some-doc-or-other_child-doc.adoc
[source,adoc]
----
...
== Subsection

yada yada yada

[[__some-doc-or-other_child-doc_other-subsection]]
== Other Subsection

yada yada yada
----

Neither of these subsections will have a button added.


== Installation

Since the extension is written in Java only AsciidoctorJ is supported.

To use it you must add it to the classpath.
In the case of Asciidoctor Maven plugin, it is enough to just add it as a dependency:

[source, xml]
----
<plugin>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-plugin</artifactId>
    <version>1.5.2</version>
    <executions>
        <execution>
            <id>output-html</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <backend>html</backend>
            </configuration>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.incode.asciidoctor.improvethisdoc</groupId>
            <artifactId>incode-asciidoctor-extension-improvethisdoc</artifactId>
            <version>0.0.2</version>
        </dependency>
    </dependencies>
</plugin>
----

Then, if required specify the following `<attributes>` (for the `asciidoctor-maven-plugin`):

[source,xml]
----
<attributes>
    ...
    <improvethisdoc.rootDir>/adocs/documentation</improvethisdoc.rootDir>
    <improvethisdoc.srcDir>/src/main/asciidoc</improvethisdoc.srcDir>
    <improvethisdoc.organisation>apache</improvethisdoc.organisation>
    <improvethisdoc.repo>isis</improvethisdoc.repo>
    <improvethisdoc.branch>master</improvethisdoc.branch>
    <improvethisdoc.label>Edit</improvethisdoc.label>
</attributes>
----

The `rootDir` and `srcDir` are used to parse the standard Asciidoc "docfile" attribute which tells the extension which file is being processed.
For example:

    C:/APACHE/isis/adocs/documentation/src/main/asciidoc/migration-notes.adoc

where:

* the value of "srcDir" is used to split between the repo name and parent directories, vs the actual `.adoc` file being processed
* the "rootDir" (which can be optionally be blank) specifies any parent directories of the maven module containing the docs being processed
* the "organisation" and "repo" are guessed from the docfile path, but can be overridden if the repo has been cloned to some other directory structure
* the "branch" specifies which branch should be edited in github
* the "label" specifies the text to appear on the button


== Release to Maven Central

The `release.sh` script automates the release process. It performs the following:

* performs a sanity check (`mvn clean install -o`) that everything builds ok
* bumps the `pom.xml` to a specified release version, and tag
* performs a double check (`mvn clean install -o`) that everything still builds ok
* releases the code using `mvn clean deploy`
* bumps the `pom.xml` to a specified release version

For example:

[source]
----
sh release.sh 0.0.2 \
              0.0.3-SNAPSHOT \
              dan@haywood-associates.co.uk \
              "this is not really my passphrase"
----

where
* `$1` is the release version
* `$2` is the snapshot version
* `$3` is the email of the secret key (`~/.gnupg/secring.gpg`) to use for signing
* `$4` is the corresponding passphrase for that secret key.

Other ways of specifying the key and passphrase are available, see the `pgp-maven-plugin`'s
http://kohsuke.org/pgp-maven-plugin/secretkey.html[documentation]).

If the script completes successfully, then push changes:

[source]
----
git push origin master && git push origin 0.0.2
----

If the script fails to complete, then identify the cause, perform a `git reset --hard` to start over and fix the issue
before trying again.  Note that in the `dom`'s `pom.xml` the `nexus-staging-maven-plugin` has the 
`autoReleaseAfterClose` setting set to `true` (to automatically stage, close and the release the repo).  You may want
to set this to `false` if debugging an issue.

According to Sonatype's guide, it takes about 10 minutes to sync, but up to 2 hours to update http://search.maven.org[search].
