= Improve this Doc


This extension post-processes HTML documentation, adding an 'Improve this Doc' button.

It adds the button in two different locations.

* It always adds a button at the top of each generated top-level document

* It also adds a button for ``include::``'d child documents.

For this second use case, there is some guess-work involved.
Because the extension is a post-processor, it does not have any visibility as to when an ``include::`` was actually performed.
It therefore makes the assumption that any `<h2>` element that has an id of `_xxx-yyy-zzz` (ie, beginning with just single underscore '_' character) corresponds to an included file.


== Example

For example, suppose we have:

.some-doc-or-other.adoc
[source,adoc]
----
[[some-doc-or-other]]
= Some Doc or Other

yada yada yada

\include::_some-doc-or-other_child-doc[leveloffset+=1]
----

and then:

._some-doc-or-other_child-doc.adoc
[source,adoc]
----
[[_some-doc-or-other_child-doc]]
= Child Doc

yada yada yada

[[__some-doc-or-other_child-doc_subsection]]
= Subsection

yada yada yada

[[__some-doc-or-other_child-doc_other-subsection]]
= Other Subsection

yada yada yada
----

Here the extension will add an 'improve this doc' button for the parent `some-doc-or-other.adoc`, and it will also add a button for the "Child Doc" heading corresponding to `_some-doc-or-other_child-doc.adoc`.

However, it won't add a button to the subsections of the child doc because their anchors start with a double underscore.


== Installation

Since the extension is written in Java only AsciidoctorJ is supported.

To use it you must add it to the classpath.
In the case of Asciidoctor Maven plugin, it is enough to just add it as a dependency:

[source, xml]
----
<plugin>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctor-maven-plugin</artifactId>
    <version>1.5.2</version>
    <executions>
        <execution>
            <id>output-html</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>process-asciidoc</goal>
            </goals>
            <configuration>
                <backend>html</backend>
            </configuration>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.incode.asciidoctor.improvethisdoc</groupId>
            <artifactId>incode-asciidoctor-extension-improvethisdoc</artifactId>
            <version>0.0.1</version>
        </dependency>
    </dependencies>
</plugin>
----

Then, if required specify the following `<attributes>` (for the `asciidoctor-maven-plugin`):

[source,xml]
----
<attributes>
    ...
    <improvethisdoc.rootDir>/adocs/documentation</improvethisdoc.rootDir>
    <improvethisdoc.srcDir>/src/main/asciidoc</improvethisdoc.srcDir>
    <improvethisdoc.organisation>apache</improvethisdoc.organisation>
    <improvethisdoc.repo>isis</improvethisdoc.repo>
    <improvethisdoc.branch>master</improvethisdoc.branch>
</attributes>
----

The `rootDir` and `srcDir` are used to parse the standard Asciidoc "docfile" attribute which tells the extension which file is being processed.
For example:

    C:/APACHE/isis/adocs/documentation/src/main/asciidoc/migration-notes.adoc

where:

* the value of "srcDir" is used to split between the repo name and parent directories, vs the actual `.adoc` file being processed
* the "rootDir" (which can be optionally be blank) specifies any parent directories of the maven module containing the docs being processed
* the "organisation" and "repo" are guessed from the docfile path, but can be overridden if the repo has been cloned to some other directory structure
* the "branch" specifies which branch should be edited in github



== Release to Maven Central

The `release.sh` script automates the release process. It performs the following:

* performs a sanity check (`mvn clean install -o`) that everything builds ok
* bumps the `pom.xml` to a specified release version, and tag
* performs a double check (`mvn clean install -o`) that everything still builds ok
* releases the code using `mvn clean deploy`
* bumps the `pom.xml` to a specified release version

For example:

[source]
----
sh release.sh 0.0.1 \
              0.0.2-SNAPSHOT \
              dan@haywood-associates.co.uk \
              "this is not really my passphrase"
----

where
* `$1` is the release version
* `$2` is the snapshot version
* `$3` is the email of the secret key (`~/.gnupg/secring.gpg`) to use for signing
* `$4` is the corresponding passphrase for that secret key.

Other ways of specifying the key and passphrase are available, see the `pgp-maven-plugin`'s
http://kohsuke.org/pgp-maven-plugin/secretkey.html[documentation]).

If the script completes successfully, then push changes:

[source]
----
git push origin master && git push origin 0.0.1
----

If the script fails to complete, then identify the cause, perform a `git reset --hard` to start over and fix the issue
before trying again.  Note that in the `dom`'s `pom.xml` the `nexus-staging-maven-plugin` has the 
`autoReleaseAfterClose` setting set to `true` (to automatically stage, close and the release the repo).  You may want
to set this to `false` if debugging an issue.

According to Sonatype's guide, it takes about 10 minutes to sync, but up to 2 hours to update http://search.maven.org[search].
